Script started on Tue 25 Nov 2014 10:46:09 PM PST
zuma% p[KPho
PhotoLab     PhotoLabTest 
zuma% PhotoLab
--------------------------------
 1:  Load a PPM image
 2:  Save an image in PPM and JPEG format
 3:  Change a color image to Black & White
 4:  Flip an image vertically
 5:  Mirror an image horizontally
 6:  Color-Filter an image
 7:  Sketch the edge of an image
 8:  Shuffle an image
 9:  Posterize the image
 10: Fill lights to an image
 11: Overlay an image 
 12: Bonus, Cut and Paste operation on image 
 13: Resize 
 14: Rotate
 15. Autotest 
  16. Add Border 
 17. Exit 
 Please make your choice: 15
Black & White tested!

VFlip tested!

HMirror tested!

Color Filter tested!

Edge Detection tested!

Shuffle tested

Posterize tested!

Fill Light  tested!

Overlay Tested!

overlay tested!

Please input start x and y coordinates for paste no 1:   1
1
Please input start x and y coordinates for paste no 2:   1
1
Please input start x and y coordinates for paste no 3:   1
1
1Cut Paste Tested! 


Rotate Tested
Resizing Large Tested 
Resizing Small Tested 
 Outer Border Tested
zuma% 1
1: Command not found.
zuma% valr[Kgrind Pho
PhotoLab*     PhotoLab.c    PhotoLabTest* PhotoLab.txt  
zuma% valgrind PhotoLabR[KTest 
==24538== Memcheck, a memory error detector
==24538== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==24538== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==24538== Command: PhotoLabTest
==24538== 
==24538== 
==24538== HEAP SUMMARY:
==24538==     in use at exit: 0 bytes in 0 blocks
==24538==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==24538== 
==24538== All heap blocks were freed -- no leaks are possible
==24538== 
==24538== For counts of detected and suppressed errors, rerun with: -v
==24538== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 6 from 6)
zuma% exit
exit

Script done on Tue 25 Nov 2014 10:46:44 PM PST
