


In this Program I actually went throught the ImageList and tried to figure that out before implementing any other part of the program. I thought my cut worked but it doesnt. I could not get Resize and otehr than that I got all the other things to work. My program is extremely messy as I did not have time to delete all my comments and all my comments contain all my working code, sorry about that. Also I did not have time to implement more than one operation . Great assignemnt would have completed with extra credit if another day was available. 
